var version = require('./lookup/version');
var versions = require('./lookup/versions');
var language = require('./lookup/language');
var users_depart = require('./lookup/users_depart');
var users_posit = require('./lookup/users_posit');
var role = require('./lookup/role');
var hospital_type = require('./lookup/hospital_type');
var hospital_class = require('./lookup/hospital_class');
var hospital_cmi = require('./lookup/hospital_cmi');
var hospital_cert_type = require('./lookup/hospital_cert_type ');
var kpi_formula = require('./lookup/kpi_formula');
var kpi_formula_input_type = require('./lookup/kpi_formula_input_type');
var kpi_interpret = require('./lookup/kpi_interpret');
var kpi_criteria = require('./lookup/kpi_criteria');
var kpi_frequency = require('./lookup/kpi_frequency');
var kpi_type = require('./lookup/kpi_type');
var kpi_matric = require('./lookup/kpi_matric');
var kpi_quality = require('./lookup/kpi_quality');
var kpi_sample = require('./lookup/kpi_sample');
var kpi_collection = require('./lookup/kpi_collection');
var kpi_input_matric = require('./lookup/kpi_input_matric');
var kpi_input_recorder = require('./lookup/kpi_input_recorder');
app.use(version);
app.use(versions);
app.use(language);
app.use(users_depart);
app.use(users_posit);
app.use(role);
app.use(hospital_type);
app.use(hospital_class);
app.use(hospital_cmi);
app.use(hospital_cert_type);
app.use(kpi_formula);
app.use(kpi_formula_input_type);
app.use(kpi_interpret);
app.use(kpi_criteria);
app.use(kpi_frequency);
app.use(kpi_type);
app.use(kpi_matric);
app.use(kpi_quality);
app.use(kpi_sample);
app.use(kpi_collection);
app.use(kpi_input_matric);
app.use(kpi_input_recorder);